// Design tokens. Values point at CSS custom properties (defined in index.css
// for [data-theme="light"|"dark"]) so the whole app re-themes instantly when
// ThemeContext flips the `data-theme` attribute — no component changes needed.
export const HEADER_HEIGHT = 68;

export const theme = {
  colors: {
    bg: "var(--bg)",
    surface: "var(--surface)",
    surfaceHover: "var(--surface-hover)",
    surfaceAlt: "var(--surface-alt)",
    border: "var(--border)",
    borderStrong: "var(--border-strong)",
    text: "var(--text)",
    textMuted: "var(--text-muted)",
    textFaint: "var(--text-faint)",
    primary: "var(--primary)",
    primaryHover: "var(--primary-hover)",
    primaryLight: "var(--primary-light)",
    primarySoft: "var(--primary-soft)",
    accent: "var(--accent)",
    success: "var(--success)",
    successLight: "var(--success-light)",
    warning: "var(--warning)",
    warningLight: "var(--warning-light)",
    danger: "var(--danger)",
    dangerLight: "var(--danger-light)",
    sidebarBg: "var(--sidebar-bg)",
    sidebarBorder: "var(--sidebar-border)",
    sidebarText: "var(--sidebar-text)",
    sidebarTextActive: "var(--sidebar-text-active)",
    headerBg: "var(--header-bg)",
    headerBgSolid: "var(--header-bg-solid)",
    headerText: "var(--header-text)",
    headerTextMuted: "var(--header-text-muted)",
    overlay: "var(--overlay)",
    glassSurface: "var(--glass-surface)",
    glassBorder: "var(--glass-border)",
  },
  font: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  mono: "'JetBrains Mono', 'SFMono-Regular', Consolas, monospace",
  radius: { sm: 6, md: 8, lg: 10, xl: 14, full: 999 },
  shadow: {
    sm: "0 1px 0 rgba(var(--shadow-color),0.04)",
    md: "0 1px 2px rgba(var(--shadow-color),0.08)",
    lg: "0 4px 16px rgba(var(--shadow-color),0.10)",
    xl: "0 16px 40px rgba(var(--shadow-color),0.16)",
    focus: "0 0 0 3px rgba(29,78,216,0.18)",
  },
};

export const layoutStyles = {
  page: {
    minHeight: "100vh",
    width: "100%",
    background: theme.colors.bg,
    fontFamily: theme.font,
    overflowX: "hidden",
    boxSizing: "border-box",
    WebkitFontSmoothing: "antialiased",
  },

  // ===== Fixed, modern top bar (used by every dashboard) =====
  topBar: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    height: HEADER_HEIGHT,
    zIndex: 500,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 28px",
    background: theme.colors.headerBg,
    boxShadow: "0 4px 24px rgba(var(--shadow-color),0.18)",
    boxSizing: "border-box",
    width: "100%",
    backdropFilter: "blur(10px)",
  },
  logoBlock: { display: "flex", alignItems: "center", gap: 12 },
  brand: { color: theme.colors.headerText, fontSize: 16, fontWeight: 700, letterSpacing: -0.2 },
  tagline: { color: theme.colors.headerTextMuted, fontSize: 10.5, marginTop: 1, fontWeight: 600, letterSpacing: 0.4 },
  userBlock: { display: "flex", alignItems: "center", gap: 8 },
  statusDot: { width: 6, height: 6, borderRadius: "50%", background: "#4ade80", boxShadow: "0 0 0 3px rgba(255,255,255,0.15)" },
  userText: {
    color: theme.colors.headerText,
    fontSize: 12.5,
    fontWeight: 600,
    fontFamily: theme.mono,
  },
  headerAvatar: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: "linear-gradient(135deg, rgba(255,255,255,0.28), rgba(255,255,255,0.1))",
    border: "1px solid rgba(255,255,255,0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontWeight: 700,
    fontSize: 13,
    letterSpacing: 0,
    flexShrink: 0,
  },

  // ===== Shell =====
  body: { display: "flex", minHeight: "100vh", width: "100%", paddingTop: HEADER_HEIGHT, boxSizing: "border-box" },

  sidebar: {
    width: 260,
    minWidth: 260,
    background: theme.colors.sidebarBg,
    borderRight: `1px solid ${theme.colors.sidebarBorder}`,
    padding: "20px 12px",
    flexShrink: 0,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    position: "fixed",
    left: 0,
    top: HEADER_HEIGHT,
    height: `calc(100vh - ${HEADER_HEIGHT}px)`,
    overflowY: "auto",
    zIndex: 450,
  },
  sidebarHeader: {
    color: theme.colors.textFaint,
    fontSize: 10,
    letterSpacing: 1.4,
    fontWeight: 700,
    padding: "0 12px 10px 12px",
    textTransform: "uppercase",
  },
  sidebarDivider: { height: 1, background: theme.colors.border, margin: "6px 0 14px 0" },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 11,
    padding: "10px 12px",
    color: theme.colors.sidebarText,
    fontSize: 13.5,
    fontWeight: 500,
    cursor: "pointer",
    borderRadius: theme.radius.sm,
    borderLeft: "3px solid transparent",
    marginBottom: 2,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    transition: "background 0.15s ease, border-color 0.15s ease, color 0.15s ease, transform 0.15s ease",
  },
  navItemActive: {
    background: theme.colors.primary,
    color: theme.colors.sidebarTextActive,
    fontWeight: 700,
    borderLeft: `3px solid ${theme.colors.primaryHover}`,
    boxShadow: "0 6px 16px rgba(29,78,216,0.32)",
  },
  navIcon: { width: 18, textAlign: "center", fontSize: 15, flexShrink: 0 },
  navBadge: {
    marginLeft: "auto",
    background: theme.colors.warning,
    color: "#fff",
    fontSize: 10,
    fontWeight: 700,
    padding: "2px 7px",
    borderRadius: theme.radius.full,
    fontFamily: theme.mono,
  },

  main: {
    flex: 1,
    minWidth: 0,
    marginLeft: 260,
    padding: "32px 40px",
    boxSizing: "border-box",
    overflowX: "hidden",
    maxWidth: "100%",
  },

  sectionTitleWrap: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 26 },
  sectionEyebrow: {
    color: theme.colors.primary,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 5,
  },
  sectionTitle: { color: theme.colors.text, fontSize: 21, fontWeight: 700, letterSpacing: -0.3, margin: 0 },
  sectionSubtitle: { color: theme.colors.textMuted, fontSize: 13.5, marginTop: 4, fontWeight: 400 },
  sectionTitleLine: { display: "none" },

  statGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14, marginBottom: 28 },
  statCard: {
    background: theme.colors.surface,
    border: `1px solid ${theme.colors.border}`,
    borderLeft: `3px solid ${theme.colors.primary}`,
    borderRadius: theme.radius.md,
    padding: "18px 20px",
    boxShadow: theme.shadow.sm,
    minWidth: 0,
    transition: "box-shadow 0.2s ease, transform 0.2s ease",
  },
  statLabel: { color: theme.colors.textMuted, fontSize: 11, fontWeight: 600, marginBottom: 10, letterSpacing: 0.2 },
  statValue: {
    color: theme.colors.text,
    fontSize: 27,
    fontWeight: 700,
    letterSpacing: -0.3,
    fontFamily: theme.mono,
    fontVariantNumeric: "tabular-nums",
  },

  panel: {
    background: theme.colors.surface,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.radius.lg,
    marginBottom: 20,
    boxShadow: theme.shadow.sm,
    overflow: "hidden",
  },
  panelHeader: {
    padding: "16px 22px",
    borderBottom: `1px solid ${theme.colors.border}`,
    color: theme.colors.text,
    fontSize: 13.5,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  panelBody: { padding: 22, overflowX: "auto", maxWidth: "100%", boxSizing: "border-box" },

  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 },
  th: {
    textAlign: "left",
    padding: "10px 14px",
    color: theme.colors.textFaint,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    borderBottom: `1px solid ${theme.colors.border}`,
    whiteSpace: "nowrap",
    fontFamily: theme.font,
  },
  td: {
    padding: "13px 14px",
    color: theme.colors.text,
    borderBottom: `1px solid ${theme.colors.bg}`,
    whiteSpace: "nowrap",
    fontWeight: 500,
    fontFamily: theme.mono,
    fontSize: 12.5,
  },

  emptyState: { color: theme.colors.textFaint, fontSize: 13, textAlign: "center", padding: "40px 0", fontFamily: theme.mono },

  btnPrimary: {
    background: theme.colors.primary,
    color: "#fff",
    border: "none",
    borderRadius: theme.radius.sm,
    padding: "10px 18px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "background 0.15s ease, transform 0.1s ease",
  },
  btnSecondary: {
    background: theme.colors.surface,
    color: theme.colors.text,
    border: `1px solid ${theme.colors.borderStrong}`,
    borderRadius: theme.radius.sm,
    padding: "10px 18px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  btnSuccess: {
    background: theme.colors.successLight,
    color: theme.colors.success,
    border: `1px solid var(--success)`,
    borderRadius: theme.radius.sm,
    padding: "7px 14px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  btnDanger: {
    background: theme.colors.dangerLight,
    color: theme.colors.danger,
    border: `1px solid var(--danger)`,
    borderRadius: theme.radius.sm,
    padding: "7px 14px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },

  input: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: theme.radius.sm,
    border: `1px solid ${theme.colors.borderStrong}`,
    background: theme.colors.surface,
    fontSize: 13.5,
    outline: "none",
    boxSizing: "border-box",
    color: theme.colors.text,
    fontFamily: "inherit",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
  },
  label: {
    display: "block",
    fontSize: 12,
    color: theme.colors.text,
    fontWeight: 600,
    marginBottom: 7,
    marginTop: 16,
  },
};

export function StatusBadge({ status }) {
  const map = {
    PENDING: { bg: theme.colors.warningLight, color: theme.colors.warning, border: "var(--warning)" },
    APPROVED: { bg: theme.colors.successLight, color: theme.colors.success, border: "var(--success)" },
    ACTIVE: { bg: theme.colors.successLight, color: theme.colors.success, border: "var(--success)" },
    GENERATED: { bg: theme.colors.warningLight, color: theme.colors.warning, border: "var(--warning)" },
    PAID: { bg: theme.colors.successLight, color: theme.colors.success, border: "var(--success)" },
    SUCCESS: { bg: theme.colors.successLight, color: theme.colors.success, border: "var(--success)" },
    REJECTED: { bg: theme.colors.dangerLight, color: theme.colors.danger, border: "var(--danger)" },
  };
  const c = map[status] || map.PENDING;
  return { background: c.bg, color: c.color, border: `1px solid ${c.border}` };
}
